<?php
/**
 * Lista normalizzata aziende clienti BAIT Service
 * Generata automaticamente da normalize_aziende.php
 * Data: 2025-08-26 09:57:50
 */

// Lista aziende normalizzata (Prima Lettera Maiuscola)
$aziende_normalizzate = [
    'Abr Green',
    'Ados SRL',
    'Amrop - G&p Consultants SRL',
    'Artlantis SRL',
    'Aspex Arl',
    'Azienda Agricola Borgo Santuletta',
    'Azienda Test',
    'Bait Service S.r.l.',
    'Be.co SRL',
    'Belloni Studio Dott. Stefano',
    'Bertocco Air Truck Technology SRL',
    'Bluebird INC.',
    'Bornoroni SRL',
    'Briot Weco Italia SPA',
    'Caf Rho',
    'Camso Italy SPA',
    'Cartiera di Rivalta SRL',
    'Claudio Ceriani',
    'Clean Room Italia SRL',
    'Clientenc',
    'Comune di Lentate Sul Seveso',
    'Con Lor SPA',
    'Corlido Italy SRL',
    'Cr Immobili Re SRL',
    'Crippa Consulting SRL',
    'D&d Ristrutturazioni',
    'De Lage Landen Renting Solutions SRL',
    'Delta 2000 SRL',
    'Destination Gusto SRL',
    'Dirk Bikkembergs SRL',
    'Dotx SRL',
    'Dueci Soluzioni SRL',
    'Electraline 3pmark SPA',
    'Electraline Cbb',
    'Elettromeccanica Centrale SRL',
    'Emmeauto Car Service SRL',
    'Emmeauto di Mariano Andrea',
    'Ep&c',
    'Eurofoam SRL',
    'Eurostudio di Leone Massimiliano',
    'Euroterminal',
    'Eva Odv',
    'Federazione Italiana Motonautica',
    'Fgb Studio',
    'Galgano Service Milano SRL',
    'Garibaldina SRL',
    'Generalfrigo SRL',
    'Givi Misure SRL',
    'Global Technology Solutions SRL',
    'Gp Autolift SRL',
    'Gp Cranes',
    'Grc Parfum SPA',
    'Grenke Locazione SRL',
    'Grr Autoricambi SRL',
    'Gruppo Toro',
    'Gt Solutions SRL',
    'Helitaly SRL',
    'Hyosung Europe SRL',
    'Hyundai Motor Company Italy SRL',
    'Il Cigno',
    'Il Mattone Immobiliare SRL',
    'Immobiliare Miva',
    'Isoterma SRL',
    'Ista Italia SRL',
    'Ital Parts',
    'Italmondo SPA',
    'Itcube Consulting SRL',
    'Itlm Services',
    'Itx Italia SRL',
    'Kmedia SRL',
    'La Batteria SRL',
    'Lbl Consulting SRL',
    'Lexart',
    'Liner Italia',
    'Lombarda Motori',
    'Ma.mi SRL',
    'Macchine Alimentari S.r.l.',
    'Maineri Federico',
    'Manes Services',
    'Marasco Avv. Pasquale Gerardo',
    'Maria Grazia Stellari',
    'Mauro Mattaini Architetto',
    'Max Moda SPA',
    'Metalmek Illuminazione SRL',
    'Microelit SPA',
    'Midas Italia SPA',
    'Mindevelopment SRL',
    'Msa - Studio Legale Accorra\'',
    'Msa Italiana SPA',
    'Msa Safety Services GMBH',
    'Mtu SAS di Camillo Rasini',
    'Multi-wing Italia SPA',
    'Nano Eco Solutions SRL',
    'Nieddu',
    'Omniaworks SNC',
    'Omnisint SRL',
    'Or.ve.ca',
    'Ortofrutticola Lainatese',
    'P.g. Dental di Potenza Giovanni',
    'Paganini Maria Ambrogia, Tabaccheria',
    'Paso SPA',
    'Perretta Giuseppe Lucio',
    'Planex Corporate Food Service Equipment SRL',
    'Productility SRL',
    'Pulinord',
    'Quattroti Dentech SRL',
    'Quattroti SRL',
    'Raimondi Cranes SPA',
    'Reale SAS',
    'Red Gloves SRL',
    'Riparaphone',
    'Rpo Electronic SRL',
    'Ruggieri Avv. Roberto',
    'S.c.a.i. SRL',
    'S.c.e.a. SRL - Studio Consulenza Aziendale',
    'Selmar Technologies SRL',
    'Selt SRL',
    'Sendabox',
    'Silanos SRL',
    'Silent Gliss Italia SRL',
    'Sinv SPA',
    'Skydental 3d',
    'Somo Produzione',
    'Spolidoro Studio Avvocato',
    'Studio Cason Villa',
    'Studio Martinelli Dr. Marco Sc. Ind. Unrhe. D. E.',
    'Studio Ricci',
    'Studio Risi Mari Donati SRL',
    'Supernova S.r.l.',
    'Switzerland Cheese Marketing Italia SRL',
    'Tate&lyle Italia SPA',
    'Tdk Foil Italy SPA',
    'Tdk-epc Italy S.r.l.',
    'Tdr Holding SRL',
    'Technicalrubber S.r.l.',
    'Tecninox S.r.l',
    'Tecnoeco SRL',
    'Temac SRL',
    'Tempoaffitti Umbria SRL',
    'Tenova SPA',
    'Termo S.p.a. Societa\' Benefit',
    'Toro Cave e Impianti S.r.l.',
    'Toro Costruzioni S.r.l.',
    'Tsc SRL',
    'Uniontransit S.r.l.',
    'Unit - Société Par Actions',
    'Utility Project SRL',
    'Valentina Baggio',
    'Wittmann Battenfeld Italia S.r.l.',
];

// Funzione per ottenere l'array
function getAziendeNormalizzate() {
    global $aziende_normalizzate;
    return $aziende_normalizzate;
}
?>